---
title: "AML hw4"
author: "Kirsten Wong"
date: "February 25, 2017"
output: html_document
---

##Problem 1 7.9
```{r, echo=TRUE}
#a
brunhild = read.csv("brunhild.txt", header=TRUE)
loglogfit = lm(log(brunhild$Sulfate) ~ log(brunhild$Hours))
plot(log(brunhild$Hours), log(brunhild$Sulfate))
abline(loglogfit$coefficients)

#b
fit = lm(brunhild$Sulfate ~ brunhild$Hours)
plot(brunhild$Hours, brunhild$Sulfate)
abline(fit$coefficients)

#c
plot(loglogfit, which=c(1,1))

```

##Problem 2 7.10
```{r, echo=TRUE}
#a
physical = read.csv("physical.txt", header=TRUE)
fit2 = lm(Mass ~ Fore+Bicep+Chest+Neck+Shoulder+Waist+Height+Calf+Thigh+Head, data=physical)

plot(fit2, which=c(1,1))

#b
cubedfit = lm(Mass^(1/3) ~ Fore+Bicep+Chest+Neck+Shoulder+Waist+Height+Calf+Thigh+Head, data=physical)
plot(cubedfit, which=c(1,1))


```

##Problem 3 7.11
```{r, echo=TRUE}
#a
abalone = read.csv("abalone.txt", header=TRUE)
fit3 = lm(Age ~ Length+Diameter+Height+Whole+Shucked+Viscera+Shell, data=abalone)
plot(fit3, which=c(1,1))

#b
fit4 = lm(Age ~ Sex+Length+Diameter+Height+Whole+Shucked+Viscera+Shell, data=abalone)
plot(fit4, which=c(1,1))

#c
fit5 = lm(log(Age) ~ Length+Diameter+Height+Whole+Shucked+Viscera+Shell, data=abalone)
plot(fit5, which=c(1,1))

#d
fit6 = lm(log(Age) ~ Sex+Length+Diameter+Height+Whole+Shucked+Viscera+Shell, data=abalone)
plot(fit6, which=c(1,1))

#f
library(glmnet)
xfactors = model.matrix(abalone$Age ~ abalone$Sex)
x = as.matrix(data.frame(abalone$Sex, abalone$Length, abalone$Diameter, abalone$Height, abalone$Whole, abalone$Shucked, abalone$Viscera, abalone$Shell, xfactors))

cvfit = cv.glmnet(x, y=abalone$Age)
plot(cvfit)
```